Repository apache/maven-parent, pull requests merged in 2024-12, with the labels that each got.

#215 Enable automatic formatter when not on CI
  pom.xml
Labels: enhancement

#220 [MNG-8453] Check dependency declarations by default
  maven-plugins/pom.xml
Labels: dependencies

#221 Add PR Automation
  .github/workflows/pr-automation.yml
Labels: maintenance
