Repository apache/maven-parent, pull requests merged in 2024-07, with the labels that each got.

#190 Remove dependency on maven-plugin-annotations to better support Maven 4 plugins
  maven-plugins/pom.xml
Labels: breaking

#191 Upgrade to Maven Fluido Skin 1.12.0
  docs/src/site/site.xml
  doxia-tools/src/site/site.xml
  pom.xml
  src/site/site.xml
Labels: dependencies

#188 [MNG-8158] Adding name to empty components section in shared site left nav
  src/site/site.xml
Labels: enhancement

#194 Disable matrix build on GitHub
  .github/workflows/maven-verify.yml
  Jenkinsfile
Labels: build

#193 Skip render empty taglist report
  pom.xml
Labels: enhancement

#195 Bump ASF parent to 33
  pom.xml
Labels: dependencies
