Repository apache/maven-parent, pull requests merged in 2025-03, with the labels that each got.

#241 Add licenseText to modello
  pom.xml
Labels: enhancement

#452 Add stale action
  .github/workflows/stale.yml
Labels: maintenance

#240 import KEYS history from svn
  KEYS
Labels: enhancement

#454 Remove link to jira from issues template
  .github/ISSUE_TEMPLATE/config.yml
Labels: maintenance

#456 Update key information of Matthias Bünger
  KEYS
Labels: maintenance

#455 Use `v@{project.version}` as tag template for releases
  .github/release-drafter.yml
  pom.xml
Labels: enhancement

#239 Introduce property maven.site.path.suffix to allow override site path
  docs/src/site/apt/index.apt.vm
  doxia-tools/pom.xml
  maven-extensions/pom.xml
  maven-plugins/pom.xml
  maven-shared-components/pom.xml
  maven-skins/pom.xml
  pom.xml
Labels: enhancement

#459 Fix asf.yaml syntax
  .asf.yaml
Labels: bug

#451 Move snapshot repositories in a profile
  .mvn/maven.config
  pom.xml
Labels: enhancement, breaking

#461 Bump parent to 34
  pom.xml
Labels: dependencies
